# Generated by Django 4.2 on 2026-05-10 15:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityHealthScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('commit_sha', models.CharField(blank=True, max_length=40)),
                ('code_security_score', models.FloatField(default=0.0)),
                ('dependency_health_score', models.FloatField(default=0.0)),
                ('runtime_security_score', models.FloatField(default=0.0)),
                ('secret_exposure_score', models.FloatField(default=0.0)),
                ('container_security_score', models.FloatField(default=0.0)),
                ('overall_score', models.FloatField(default=0.0)),
                ('grade', models.CharField(default='F', max_length=2)),
                ('total_vulnerabilities', models.IntegerField(default=0)),
                ('critical_count', models.IntegerField(default=0)),
                ('high_count', models.IntegerField(default=0)),
                ('medium_count', models.IntegerField(default=0)),
                ('low_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('sast', 'SAST (Static Analysis)'), ('sca', 'SCA (Dependency Analysis)'), ('dast', 'DAST (Dynamic Analysis)'), ('secret', 'Secret Scanning'), ('container', 'Container Scanning')], max_length=20)),
                ('tool_name', models.CharField(max_length=50)),
                ('scan_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('commit_sha', models.CharField(blank=True, max_length=40)),
                ('branch', models.CharField(default='main', max_length=100)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('raw_report', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-scan_date'],
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vulnerability_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Informational')], max_length=20)),
                ('confidence', models.CharField(default='medium', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('code_snippet', models.TextField(blank=True)),
                ('cwe_id', models.CharField(blank=True, max_length=20)),
                ('cvss_score', models.FloatField(blank=True, null=True)),
                ('references', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('open', 'Open'), ('confirmed', 'Confirmed'), ('false_positive', 'False Positive'), ('fixed', 'Fixed'), ('accepted_risk', 'Accepted Risk')], default='open', max_length=20)),
                ('first_detected', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('calculated_risk_score', models.FloatField(default=0.0)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='security_intelligence.securityscan')),
            ],
            options={
                'ordering': ['-calculated_risk_score', '-severity'],
            },
        ),
        migrations.CreateModel(
            name='VulnerabilityCorrelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(default=0.0)),
                ('correlation_method', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('correlated_vulnerabilities', models.ManyToManyField(related_name='correlations_as_correlated', to='security_intelligence.vulnerability')),
                ('primary_vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlations_as_primary', to='security_intelligence.vulnerability')),
            ],
        ),
        migrations.CreateModel(
            name='RemediationSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('fix_description', models.TextField()),
                ('code_example', models.TextField(blank=True)),
                ('references', models.JSONField(default=list)),
                ('estimated_effort', models.CharField(default='medium', max_length=20)),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='security_intelligence.vulnerability')),
            ],
            options={
                'ordering': ['-priority'],
            },
        ),
    ]
